### ISSUE TITLE
Two way anova

### ISSUE THREAD

**Issue by gabrielelanaro** [aloctavodia/Doing_bayesian_data_analysis#4]
Hi! I was wondering if you managed to get the Salary program (two way anova) working. I'm trying really hard but I don't seem to get an answer similar to the book. (for example there's no main effect on FT1 FT2 and FT3, plus so many convergence problems)

**Comment by aloctavodia** [comment]
Hi! Sorry, I didn't have time to go beyond chapter 18. I will resume porting the code at the end/begining of March/April.

**Comment by aloctavodia** [comment]
Hi Gabriele.
Did you manage to solve the problem? I just start porting the code from chapter 19.

**Comment by gabrielelanaro** [comment]
I was able to solve the problem but I don't remember where I put the code. However I have an old version that goes something like this: 

    salary = pd.read_csv("/home/gabriele/workspace/bayesiandata/Salary.csv")

    x = salary.Post.copy()
    x[x=='FT1'] = 0
    x[x=='FT2'] = 1
    x[x=='FT3'] = 2
    x = x.values.astype('int')

    x1 = salary.Org.copy()
    x1[x1=='BFIN'] = 0
    x1[x1=='CEDP'] = 1
    x1[x1=='CHEM'] = 2
    x1[x1=='THTR'] = 3
    x1 = x1.values.astype('int')

    y = salary.Salary.values.astype('float')

    z = (y - np.mean(y))/np.std(y)

    # The model
    with pm.Model() as model:

        a1_SD_unabs = pm.T('a1_SD_unabs', mu=0, lam=0.001, nu=1)
        #a1_SD = abs(a1_SD_unabs) + 0.1
        a1_SD = a1_SD_unabs + 0.1

        a1tau = 1 / a1_SD**2

        a2_SD_unabs = pm.T('a2_SD_unabs', mu=0, lam=0.001, nu=1)
        #a2_SD = abs(a2_SD_unabs) + 0.1
        a2_SD = a2_SD_unabs + 0.1

        a2tau = 1 / a2_SD**2

        a12_SD_unabs = pm.T('a12_SD_unabs', mu=0, lam=0.001, nu=1)
        #a2_SD = abs(a2_SD_unabs) + 0.1
        a12_SD = a12_SD_unabs + 0.1

        a12tau = 1 / a12_SD**2


        a0 = pm.Normal('a0', 0, 0.001)
        a1 = pm.Normal('a1', 0, a1tau, shape=(3, 1))
        a2 = pm.Normal('a2', 0, a2tau, shape=(1, 4))
        a12 = pm.Normal('a12', 0, a12tau, shape=(3, 4))

        # Mean for each factor
        mu = a0 + a1 + a2 + a12

        sigma = pm.Uniform('sigma', 0, 10)
        tau = 1/sigma**2

        # Salary
        y_obs = pm.Normal('y', mu[x, x1], tau, observed=z)

        # MCMC chain
        start = pm.find_MAP()
        steps = [pm.HamiltonianMC(vars=model.vars), pm.Metropolis()]
        trace = pm.sample(500000, steps, start=start)

However this solution has unconstrained parameters ``a`` which are highly correlated. However, what I found is that by applying the sum-to-zero constraint (and that's the part I can't manage to retrieve), the autocorrelation disappears.

**Comment by aloctavodia** [comment]
Yeah, I have the same problem with the highly correlated a.

Using this sampler combination 

```python
 step0 = pm.NUTS([sigma, a0])
 step1 = pm.Metropolis([a1_SD_unabs, a2_SD_unabs, a1a2_SD_unabs, a1, a2, a1a2])
```

and a thinning of ~500 I manage to get values "close" to the ones in the book, but not close enough.

I will keep exploring this problem.

**Comment by aloctavodia** [comment]
I solve the sampling problem applying the sum-to-zero constrain (as you suggested). Thanks for the pointer. ASAP I will upload the whole code.

```python
with pm.Model() as model:
    # define the hyperpriors
    a1_SD_unabs = pm.T('a1_SD_unabs', mu=0, lam=0.001, nu=1)
    a1_SD = abs(a1_SD_unabs) + 0.1
    a1tau = 1 / a1_SD**2

    a2_SD_unabs = pm.T('a2_SD_unabs', mu=0, lam=0.001, nu=1)
    a2_SD = abs(a2_SD_unabs) + 0.1
    a2tau = 1 / a2_SD**2
    
    a1a2_SD_unabs = pm.T('a1a2_SD_unabs', mu=0, lam=0.001, nu=1)
    a1a2_SD = abs(a1a2_SD_unabs) + 0.1
    a1a2tau = 1 / a1a2_SD**2


    # define the priors
    sigma = pm.Uniform('sigma', 0, 10) # y values are assumed to be standardized
    tau = 1 / sigma**2
    
    a0 = pm.Normal('a0', mu=0, tau=0.001) # y values are assumed to be standardized
   
    a1 = pm.Normal('a1', mu=0 , tau=a1tau, shape=Nx1Lvl)
    a2 = pm.Normal('a2', mu=0 , tau=a2tau, shape=Nx2Lvl)
    a1a2 = pm.Normal('a1a2', mu=0 , tau=a1a2tau, shape=[Nx1Lvl, Nx2Lvl])

    b1 = pm.Deterministic('b1', a1 - T.mean(a1))
    b2 = pm.Deterministic('b2', a2 - T.mean(a2))
    b1b2 = pm.Deterministic('b1b2', a1a2 - T.mean(a1a2))
    
    mu = a0 + b1[x1] + b2[x2] + b1b2[x1, x2]
 
    # define the likelihood
    yl = pm.Normal('yl', mu=mu, tau=tau, observed=z)
```
